### ISSUE TITLE
Create a docker-compose.yml file for deploying it on a vps 

### ISSUE THREAD

**Issue by bolavefasfas** [alist-org/alist#2067]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [] I'm sure there are no duplicate issues or discussions. # their are discussions but incomplete 
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

Create a docker-compose.yml file for deploying it on a vps 

### Suggested solution / 实现思路

Create a docker-compose.yml file for deploying it on a vps 
With multiple database support or database of choice support
like
1. mysql
2. postgress
3. mongodb
4.and from environment variable for external database as well if we dont want to use locally hosted database 

```
version: "3.3"
services:
    alist:
        restart: always
        volumes:
            - /etc/alist:/opt/alist/data
        ports:
            - "5244:5244"
        container_name: alist
        image: xhofe/alist:latest
```

I created this it is working perfectly with local database I would like to use external database in this 
as you already have a docker file its easy to create a docker-compose.yml 

From any of these sites 

- https://db4free.net/
- https://remotemysql.com/
- https://www.freesqldatabase.com/
- https://planetscale.com/
- https://bit.io/
- https://www.elephantsql.com/
- https://scalingo.com/
- http://cloud.yugabyte.com/

and local postgress or my sql with docker images
