### ISSUE TITLE
3.7.1 本地存储 permission denied

### ISSUE THREAD

**Issue by oevery** [alist-org/alist#2841]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.7.1

### Driver used / 使用的存储驱动

本地存储

### Describe the bug / 问题描述

本地存储 failed get objs: failed to list objs: open xxx permission denied。
进入容器是可以看见目录并且正常访问的，只有 alist 界面 permission denied。

### Reproduction / 复现链接

none

**Comment by Xhofe** [comment]
https://alist.nn.ci/guide/install/docker.html#user-group-identifiers

**Comment by oevery** [comment]
> https://alist.nn.ci/guide/install/docker.html#user-group-identifiers

设置过，还是不行，而且切换到前一个版本就没有问题了。

**Comment by Xhofe** [comment]
> > https://alist.nn.ci/guide/install/docker.html#user-group-identifiers
> 
> 设置过，还是不行，而且切换到前一个版本就没有问题了。

检查你的文件夹权限和docker启动镜像的用户，新开的容器测试没有问题：http://47.87.163.158:5244/local

**Comment by oevery** [comment]
已解决，我在 docker compose 中配置了 user 选项，未配置 `environment` 中的选项，配置 uid gid 后问题解决。

**Comment by liang0222** [comment]
> 已解决，我在 docker compose 中配置了 user 选项，未配置 中的选项，配置 uid gid 后问题解决。`environment`

怎么设置 可以发来参考吗 分享配置

**Comment by oevery** [comment]
> > 已解决，我在 docker compose 中配置了 user 选项，未配置 中的选项，配置 uid gid 后问题解决。`environment`
> 
> 怎么设置 可以发来参考吗 分享配置

```yaml
version: "3"

services:
  alist:
    image: xhofe/alist:latest
    container_name: alist
    restart: unless-stopped
    ports:
      - "5244:5244"
    environment:
      - PUID=1000
      - PGID=1000
      # - UMASK=022
      - TZ=Asia/Shanghai
 ```
