### ISSUE TITLE
自定义头部（或自定义内容）遮挡了全屏预览文件

### ISSUE THREAD

**Issue by Febtw** [alist-org/alist#3058]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.8.0

### Driver used / 使用的存储驱动

Onedrive

### Describe the bug / 问题描述

我在“自定义头部”（或“自定义内容”）中添加了aplayer音乐播放器，在预览文件全屏（ 如excel、pdf 等文件）时，aplayer会遮挡文件，而观看视频时自带的视频播放器的全屏功能则能覆盖aplayer。
希望预览文件全屏可以覆盖“自定义内容”

1、“自定义内容” 的设置
![image](https://user-images.githubusercontent.com/96163355/212583451-a5d0f09e-8ddd-4d8c-90fc-747ce8b3c78d.png)
```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.css">
<script src="https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/meting@2.0.1/dist/Meting.min.js"></script>
<meting-js 
	server="netease" 
	type="playlist" 
	id="3778678"
	fixed="true" 
	autoplay="false"
	loop="all"
	order="random"
	preload="auto"
	list-folded="ture"
	volume="0.4"
	list-max-height="360px">
</meting-js>
```

2、excel全屏预览被aplayer遮挡
![image](https://user-images.githubusercontent.com/96163355/212585011-5e7e0672-221b-4118-a75a-24df0e7de69e.png)

3、自带视频播放器全屏不会被遮挡
![image](https://user-images.githubusercontent.com/96163355/212584635-0baacc6c-7ab5-4238-a947-ecc39d8427be.png)

### Reproduction / 复现链接

无

**Comment by anwen-anyi** [comment]
把下面的哪个放到自定义头部里面去...而且你这是属于自己的问题 不是BUG 请勿乱用...自己加标签 自行关闭issue吧..

----
```css
/*音乐播放器进一步进行隐藏*/
 .aplayer.aplayer-fixed.aplayer-narrow .aplayer-body {
    left: -66px!important;
}
.aplayer.aplayer-fixed.aplayer-narrow .aplayer-body:hover {
    left: 0!important;
}
```
