### ISSUE TITLE
docker compose 安装，密码是多少？

### ISSUE THREAD

**Issue by LittleNewton** [alist-org/alist#3488]
看不到密码。
采用docker compose安装。

```
version: "3.3"
services:
  alist:
    image: 'xhofe/alist:latest'
    container_name: alist
    hostname: alist
    networks:
      - nginxproxymanager
    volumes:
      - '/home/me/alist:/opt/alist/data'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
    restart: unless-stopped

networks:
  nginxproxymanager:
    name: nginxproxymanager_default
    external: true

```

data/config里有个jwt_secret，试过了也不行。
docker logs alist 也无法输出密码。只有寥寥几行。

这么大个项目怎么连初始密码都没有？
