### ISSUE TITLE
能否支持自动切换深色模式和浅色模式

### ISSUE THREAD

**Issue by chaofan2685** [alist-org/alist#3641]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

目前Alist支持手动点击切换深色模式和浅色模式，希望能根据浏览器或是系统配色方案支持自动切换深色模式和浅色模式。

### Suggested solution / 实现思路

利用css中的prefers-color-scheme属性
```css
/* 根据系统的深色模式响应深色变量 */
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #ffff;
    --textColor: #282c34;
    --borderColor: #2c2c3a;
  }
}
@media (prefers-color-scheme: light) {
  :root {
    --bg: #282c34;
    --textColor: #efefef;
    --borderColor: #2c2c3a;
  }
}
```
