### ISSUE TITLE
外置数据库连接问题

### ISSUE THREAD

**Issue by 443126500** [alist-org/alist#4710]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

外置数据库如果重启，偶尔会导致alist连接不上数据库，导致无法启动，且好像不会再次进行重新连接，希望可以增加因数据库连接不上启动失败后定时尝试重新启动。
另外还有那个公告，会自动消失，电脑端显示正常，手机端那个提示窗后面的那个关闭按钮会影响公告的阅读，希望可以设置公告显示的时长，或者优化下那个关闭按钮的显示

**Comment by anwen-anyi** [comment]
1. 重启后你你的AList应该延时启动 可能你的网络还没连接上 导致无法连接到外置数据库（[配置文件](https://alist.nn.ci/zh/config/configuration.html#delayed-start)）


2. 公告 `X` 的问题可以使用CSS将 `X`用CSS去掉
```css
<style>
/* 去除通知栏 右上角 X */
.notify-render .hope-close-button{
    display: none;
}
</style>
```
如果你不使用公告的话可以将公告清空就会不显示了
