### ISSUE TITLE
下载磁力链接提示没有权限创建临时下载目录

### ISSUE THREAD

**Issue by jxjxjhjh** [alist-org/alist#5139]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [ ] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.26.0 及前面两三个版本

### Driver used / 使用的存储驱动

本机和阿里云都试过

### Describe the bug / 问题描述

failed to download 7bf971a29a317d07, error: Failed to make the directory /opt/alist/data/temp/aria2/b8766c37-2712-4695-a3e6-6638c5d9ed84, cause: Permission denied
不映射、映射目录加777权限、映射目录归属ROOT或1000用户都不行

### Reproduction / 复现链接

无

### Config / 配置

无

**Comment by xhofe** [comment]
怎么安装的

**Comment by jxjxjhjh** [comment]
> 

```
version: '3.3'
services:
    alist:
        restart: always
        volumes:
            - '/home/Notes/alist:/opt/alist/data'
            - '/home/alist:/opt/alist/data/temp/aria2'
            - '/home:/home'
        ports:
            - '1203:5244'
        environment:
            - PUID=0
            - PGID=0
            - UMASK=022
        container_name: alist
        image: 'xhofe/alist'
```

aria2是用的官方提供的aria2-pro加ariang一起的docker-compose.yml文件安装的
