### ISSUE TITLE
115 health check is flawed

### ISSUE THREAD

**Issue by gengjiawen** [alist-org/alist#5993]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

xhofe/alist-aria2:v3.30.0

### Driver used / 使用的存储驱动

115

### Describe the bug / 问题描述

Health check 有缺陷
## storage 页面

![CleanShot 2024-02-03 at 15 16 37@2x](https://github.com/alist-org/alist/assets/3759816/7f15ddf7-130f-402f-9cf1-5ea67897d841)
## 查看文件页面
![CleanShot 2024-02-03 at 15 16 48@2x](https://github.com/alist-org/alist/assets/3759816/0d11d347-d315-41df-a04d-4b512dcd31a5)

### Reproduction / 复现链接

rt

### Config / 配置

```
version: '3.3'
services:
    alist:
        restart: always
        volumes:
            - '/etc/alist:/opt/alist/data'
        ports:
            - '2052:5244'
            - '6800:6800'
        environment:
            - PUID=0
            - PGID=0
            - UMASK=022
        container_name: alist
        image: 'xhofe/alist-aria2:v3.30.0'
```
