### ISSUE TITLE
重启容器时config.json的修改被回滚

### ISSUE THREAD

**Issue by SwingCosmic** [alist-org/alist#6432]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.9.2触发，更新到v3.34.0复现（全新重装v3.34.0可以解决）

### Driver used / 使用的存储驱动

local

### Describe the bug / 问题描述

使用k8s + OpenEBS local卷 + PVC挂载本地硬盘文件夹到容器内的`/opt/alist/data`，可读写。
第一次启动前文件夹是空的

当删除Pod或者进行伸缩以重启容器时，config.json的内容被还原到初始状态

### Reproduction / 复现链接

1. 将alist副本数调整为0，取消data目录的挂载
2. 直接修改openebs所挂载的物理路径`/var/openebs/local/pvc-xxxxxxxx/config.json`的文件，修改配置，例如s3配置并启用，保存
3. 使用其他deployment挂载该pvc以进行测试，使用终端访问可以确认该文件内容确实发生了修改，然后取消挂载
4. 重新对alist的`/opt/alist/data`目录挂载pvc，并将副本调整为1启动
5. alist并未增加s3的配置菜单，并且直接访问硬盘物理文件发现内容被回滚

### Config / 配置

初始配置(v3.9.2)

```json
{
  "force": false,
  "address": "0.0.0.0",
  "port": 5244,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "xxxx",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "https": false,
    "cert_file": "",
    "key_file": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 10,
    "max_backups": 5,
    "max_age": 28,
    "compress": false
  },
  "max_connections": 0
}
```

k8s deployment

```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: alist
  namespace: default
  labels:
    app: alist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alist
  template:
    metadata:
      labels:
        app: alist
    spec:
      volumes:
        - name: volume-xl4o13
          persistentVolumeClaim:
            claimName: alist-config
        - name: volume-wyddal
          persistentVolumeClaim:
            claimName: alist-data
      containers:
        - name: container-z2joj2
          image: 'xhofe/alist:v3.9.2'
          ports:
            - name: tcp-5244
              containerPort: 5244
              protocol: TCP
          env:
            - name: PGID
              valueFrom:
                configMapKeyRef:
                  name: alist-env
                  key: PGID
            - name: PUID
              valueFrom:
                configMapKeyRef:
                  name: alist-env
                  key: PUID
            - name: UMASK
              valueFrom:
                configMapKeyRef:
                  name: alist-env
                  key: UMASK
          resources: {}
          volumeMounts:
            - name: volume-xl4o13
              mountPath: /opt/alist/data
            - name: volume-wyddal
              mountPath: /data
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: alist-data
  namespace: default
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: openebs.io/local
    volume.kubernetes.io/selected-node: yourhost.com
    volume.kubernetes.io/storage-provisioner: openebs.io/local
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi
  volumeName: pvc-xxxxxx1
  storageClassName: local
  volumeMode: Filesystem

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: alist-config
  namespace: default
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: openebs.io/local
    volume.kubernetes.io/selected-node: yourhost.com
    volume.kubernetes.io/storage-provisioner: openebs.io/local
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pvc-xxxxxx2
  storageClassName: local
  volumeMode: Filesystem

```

### Logs / 日志

```
 INFO[2024-05-08 06:49:14] reading config file: data/config.json        

 INFO[2024-05-08 06:49:14] load config from env with prefix:            

 INFO[2024-05-08 06:49:14] init logrus...                               

 WARN[2024-05-08 06:49:15] not enable search                            

 INFO[2024-05-08 06:49:15] start server @ 0.0.0.0:5244                  

 INFO[2024-05-08 06:49:15] success load storage: [/nfs], driver: [Local] 

 INFO[2024-05-08 06:49:15] Aria2 not ready.    
```
