### ISSUE TITLE
webdav 重命名文件会触发 502 错误

### ISSUE THREAD

**Issue by VergilGao** [alist-org/alist#6586]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.35.0

### Driver used / 使用的存储驱动

本机存储

### Describe the bug / 问题描述

使用 webdav 挂载后，重命名文件，返回 502 错误。
在网页端重命名文件并未触发此问题。

### Reproduction / 复现链接

alist部署在内网，没有对外公开的接口。

![Snipaste_2024-06-07_12-37-49](https://github.com/alist-org/alist/assets/8655163/14163987-c593-4ded-b991-3e329934d0b2)

### Config / 配置

使用 docker 部署，配置文件为默认：
```
  alist:
    image: xhofe/alist
    container_name: alist
    environment:
      - PUID=99
      - PGID=100
      - UMASK=002
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/pool_zero/appdata/alist:/opt/alist/data
      - /mnt/user/dav:/mnt/data
    networks:
      webapp:
        ipv4_address: 192.168.32.4
    restart: unless-stopped
```

### Logs / 日志

```
$ cat access.log| grep "VergilGao" | tail
192.168.20.1 - keepass_xiaoyu [07/Jun/2024:12:31:38 +0800] "PUT /dav/VergilGao.kdbx.tmp HTTP/1.1" 201 32 "-" "-"
192.168.20.1 - keepass_xiaoyu [07/Jun/2024:12:31:38 +0800] "GET /dav/VergilGao.kdbx HTTP/1.1" 200 53543 "-" "-"
192.168.20.1 - keepass_xiaoyu [07/Jun/2024:12:31:38 +0800] "DELETE /dav/VergilGao.kdbx HTTP/1.1" 204 0 "-" "-"
192.168.20.1 - keepass_xiaoyu [07/Jun/2024:12:31:38 +0800] "MOVE /dav/VergilGao.kdbx.tmp HTTP/1.1" 502 11 "-" "-"
192.168.20.1 - keepass_xiaoyu [07/Jun/2024:12:33:55 +0800] "MOVE /dav/VergilGao.kdbx.tmp HTTP/2.0" 502 11 "-" "Microsoft-WebDAV-MiniRedir/10.0.22631"
192.168.20.1 - keepass_xiaoyu [07/Jun/2024:12:35:56 +0800] "GET /dav/VergilGao.kdbx HTTP/1.1" 404 9 "-" "-"
192.168.20.1 - keepass_xiaoyu [07/Jun/2024:12:35:56 +0800] "PUT /dav/VergilGao.kdbx.tmp HTTP/1.1" 201 32 "-" "-"
192.168.20.1 - keepass_xiaoyu [07/Jun/2024:12:35:56 +0800] "GET /dav/VergilGao.kdbx HTTP/1.1" 404 9 "-" "-"
192.168.20.1 - keepass_xiaoyu [07/Jun/2024:12:35:56 +0800] "MOVE /dav/VergilGao.kdbx.tmp HTTP/1.1" 502 11 "-" "-"
192.168.20.1 - keepass_xiaoyu [07/Jun/2024:12:36:14 +0800] "MOVE /dav/VergilGao.kdbx.tmp HTTP/2.0" 502 11 "-" "Microsoft-WebDAV-MiniRedir/10.0.22631"
```
