### ISSUE TITLE
视频播放失败

### ISSUE THREAD

**Issue by awsl1414** [alist-org/alist#7089]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.36.0

### Driver used / 使用的存储驱动

本机存储

### Describe the bug / 问题描述

大文件（5g以上）视频无法播放

### Reproduction / 复现链接

点击一个mkv大视频，等待加载，右上角显示重新连接，然后预览中心出现播放失败符号
![image](https://github.com/user-attachments/assets/1d7cc9b3-2535-4e6f-8e47-8c25a7ad1e57)
![image](https://github.com/user-attachments/assets/0c7b8b1c-2554-42a6-8796-735597e416e3)

### Config / 配置

docker-compose.yam
```
services:
    alist:
        image: 'xhofe/alist:latest'
        container_name: alist
        volumes:
            - '/etc/alist:/opt/alist/data'
            - '/root/alist_data:/root/alist_data'
        ports:
            - '5244:5244'
        environment:
            - PUID=0
            - PGID=0
            - UMASK=022
        restart: unless-stopped
```
![image](https://github.com/user-attachments/assets/b43cb1ac-9f39-42f7-931d-d0032ff722c5)

![image](https://github.com/user-attachments/assets/67811eb5-fcc1-451b-8e80-25063cbca263)

### Logs / 日志

![image](https://github.com/user-attachments/assets/9c90636b-959f-494a-91fa-65a15c72907a)
![image](https://github.com/user-attachments/assets/f492beea-7797-4111-a399-6c0d9f175797)
